version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
  aws-serverless: circleci/aws-serverless@1.0.1
jobs:
  aws-cli-create-bucket:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: aws s3 mb s3://travis-reed-hackisu-lambda-pre-code
workflows:
  deploy:
    jobs:
      - aws-cli-create-bucket:
          context: AWS
